[project]
name = "gt-substrate-predictor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch[cuda]>=2.9.0",
    "wandb>=0.22.3",
]
